
lb_fecha_ini = "Fecha inicial"
lb_fecha_fin = "Fecha final"
lb_empresa = "Empresa"
lb_unidad_negocio = "Unidad de Negocio"
lb_entidad = "entidad"
lb_entidades = "entidades"
lb_instalacion = "instalacion"
lb_instalaciones = "instalaciones"
lb_instalacion_id = "instalacion_id"
lb_protocolo = "Protocolo"
lb_dispo_ponderada_empresa = "Disponibilidad ponderada Empresa"
lb_dispo_ponderada_unidad = "Disponibilidad ponderada Unidad de Negocio"
lb_dispo_promedio_instalacion = "Disponibilidad promedio Instalación"
lb_no_seniales = "No. señales"
lb_falladas = "Falladas"
lb_latitud = "Latitud"
lb_longitud = "Longitud"
lb_tag_name = "tag_name"
lb_indisponible_minutos = "indisponible_minutos"
lb_indisponible_minutos_promedio = "indisponible_minutos_promedio"
lb_periodo_evaluacion = "Periodo evaluación"
details_columns = [lb_fecha_ini, lb_fecha_fin, lb_empresa, lb_unidad_negocio, lb_instalacion, lb_protocolo,
                   lb_dispo_ponderada_empresa,
                   lb_dispo_ponderada_unidad, lb_dispo_promedio_instalacion, lb_no_seniales, lb_latitud,
                   lb_longitud]

lb_numero_tags = "numero_tags"
lb_numero_tags_procesadas = "numero_tags_procesadas"
lb_numero_bahias_procesadas = "numero_bahias_procesadas"
lb_numero_instalaciones_procesadas = "numero_instalaciones_procesadas"
lb_numero_entidades_procesadas = "numero_entidades_procesadas"
lb_numero_nodos_procesados = "numero_nodos_procesados"
lb_tags_fallidas = "tags_fallidas"
lb_bahias_fallidas = "bahias_fallidas"
lb_instalaciones_fallidas = "instalaciones_fallidas"
lb_entidades_fallidas = "entidades_fallidas"
lb_nodos_fallidos = "nodos_fallidos"
lb_detalle = "detalle"